---
topic: "Topic 1: UAS Basics"
title: "B. Rules and regulations for UAS operations"
subtitle: "Topic 1: UAS Basics"
date: 8/26/2024
assignment-due-date: 9/2/2024
---

## Outline

* levels of regulatory authority
* Small UAS Rule (Part 107)
* UAS authorizations to fly
* types of airspace and restrictions to flight
* current information resources 

## Lecture

* Lecture Slides: [Rules and Regulations](lectures/lecture_1b.qmd)
* Lecture Recording: TBD
* Past Videos (2017)
    * [Part 1](https://youtu.be/Pf_kwEq6too?feature=shared)
    * [Part 2](https://youtu.be/JUM93NZlukI?feature=shared)
    * [Part 3](https://youtu.be/goewibtKfgQ?feature=shared)
    * [Part 4](https://youtu.be/KQ02OTxmlNA?feature=shared)
    * [Part 5](https://youtu.be/lW58hD165sY?feature=shared)

### Supplemental materials

* [FAA Unmanned Aircraft Systems](https://www.faa.gov/uas/)
* [Becoming a Pilot sUAS Rule (Part 107)](https://www.faa.gov/uas/commercial_operators/become_a_drone_pilot/)
* [Where can I find study materials for the Part 107 aeronautical knowledge test?](https://www.faa.gov/faq/where-can-i-find-study-materials-part-107-aeronautical-knowledge-test)
* [Operating UAS in North Carolina](https://www.ncdot.gov/aviation/uas/)
* [UAS Activities at NC State: Rules and Regulations](https://oit.ncsu.edu/about/units/campus-it/rules-and-regulations/uas/)
* Aeronautical charts and related georeferenced data
    * [View digital aeronautical charts](https://vfrmap.com/)
    * [Skyvector](https://skyvector.com/):charts, airspace and airport information for pilots
    * [Download georeferenced digital aeronautical charts](http://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/vfr/), download Charlotte for NC chart
    * [FAA data innovation center](https://www.faa.gov/nextgen/equipadsb/research/airspace/media/2020ADS-BAirspaceMap.kmz), airspace type vector data in shape and kmz format 
* Weather data
    * [Aviation Weather Center](https://www.aviationweather.gov/), interactive METAR, TAFs and other NOAA NWS resources 
* Other helpful material
    * [Educational use of UAS](https://drive.google.com/open?id=0B8j08KoSleFQd3gzdElMOHJKMHM) 


## Assignment

UAS Rule Part 107 test: select 5 questions and briefly explain the correct answers in the the provided [sample questions](https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/uag_questions.pdf) 

## Homework

Prepare brief report on the selected section of the Part 107 test - 5 questions and answers with explanation. 