---
topic: "Topic 4: GIS Analytics"
title: "B. Point cloud data analysis"
subtitle: "Topic 4: GIS Analytics"
date: 9/23/2024
assignment-due-date: 10/23/2024
---

# Point cloud data analysis

## Outline
- Characteristics of UAS SfM and lidar-based point cloud data
- Point cloud data representation and formats
- Point cloud data processing, visualization, and analysis
- Bare earth point extraction
- Working with classified point clouds
- Computing DEM and topographic analysis
- Voxel-based analysis and vertical profiles

## Lecture
- [Lecture slides](./lectures/lecture_4b.qmd)
- Lecture Recording: [Fall 2024]({{< var recordings.topic4.lecture4b >}}) (NCSU Only)
<!-- - In-Class Recording: [Fall 2024]({{< var recordings.topic4.assignment4b >}}) (NCSU Only) -->

## Supplemental materials
- [Processing point clouds in GRASS GIS](https://grasswiki.osgeo.org/wiki/Processing_lidar_and_UAV_point_clouds_in_GRASS_GIS_(workshop_at_FOSS4G_Boston_2017)), workshop presented at FOSS4G conference in Boston in 2017 (start with the section "Binning the point cloud").
- [USGS 3DEP Data View](https://usgs.entwine.io/)
- [LAS specification v1.4-R13](https://www.asprs.org/a/society/committees/standards/LAS_1_4_r13.pdf), July 2013
- [Lidar and INS](https://www.oxts.com/technical-notes/why-use-an-inertial-navigation-system-ins-with-a-lidar/)

- Past Lecture recordings:
  - [Properties](https://youtu.be/X-27KYsG6kE)
  - [Processing](https://youtu.be/yKFSodBHDRg)
  - [DEMs and voxel models](https://youtu.be/MU4wSk_M8yk)


## Assignment & Homework

[Assignment 4B](assignments/assignment_4b.qmd)
 