---
title: "Assignment 2A"
subtitle: "From images to 3D models: Photogrammetry and Structure from Motion concepts"
assignment-due-date: 9/30/2024
---

## Task

Perform an experiment to investigate impact of the number and orientation of photos, light, as well as shape and features of a photographed object on its 3D reconstruction from multiple overlapping imagery.


## Homework

Prepare short report on your 3D modeling experiment.

3D models from previous courses are available on [OsgeoLab Skechfab account](https://sketchfab.com/osgeolab/collections/classroom-models). If you would like your model to be added to the collectionl please indicate at the end of your report "I agree for my 3D model to be uploaded to the OsgeoLab Skechfab collection and I want(/don't want) my name to be listed as an author in the model description" and submit on through moodle your 3D model (preferably in the .obj format with accompaning .mtl and .jpg files, or check [other formats supported by Sketchfab](https://help.sketchfab.com/hc/en-us/articles/202508396-3D-File-Formats?page=3#3d-formats))

