---
topic: "Topic 3: UAS Flight Planning"
title: "UAS Flight Planning"
subtitle: "Topic 3: UAS Flight Planning"
date: 9/15/2025
activity: Lecture/Assignment
assignment-due-date: 10/1/2025
---

## Outline

- Defining the data collection purpose
- Survey area, take off and landing locations
- Terrain and weather conditions
- Safe flight
- Flight parameters
- Flight planning and management platforms

## Lecture

- [Flight planning introduction](lectures/lecture_3a.qmd)
- [Lecture Recording]({{< var recordings.topic3.lecture3 >}}) (NCSU Only)
- [Assignment Recording]({{< var recordings.topic3.assignment3 >}}) (NCSU Only)
<!-- - Recording of the Intro to flight planning in eMotion software -->

## Supplemental materials

### Flight - watch the following if you were unable to attend the flight session

- Fixed wing flight (eBee X): [set up](https://youtu.be/jBgrxB6-pj4), [launch](https://youtu.be/BlsHC1kSrE4) and [landing](https://youtu.be/_9o2zZMSXOw)
- Vertical take-off (VTOL) fixed wing flight with [Wingtra drone](https://youtu.be/ra1sMJzibjY)
- Rotary wing flight (Phantom)
    - Flight with [Drone Deploy flight](https://youtu.be/1OnZPV1HeQs) planning app
    - Flight with [Pix4D Capture flight](https://youtu.be/nV_7d6YdYTc) planning app

### Flight planning and management platforms

#### Commerical Options
  - [DroneDeploy](https://www.dronedeploy.com/)
  - [Pix4Dcapture Pro](https://www.pix4d.com/product/pix4dcapture/)
  - [DJI GS PRO](https://www.dji.com/ground-station-pro)
  - [UgCS](https://www.sphengineering.com/flight-planning/ugcs)
  - [DroneLink](https://www.dronelink.com/)

#### Open Source Options

  - [QGroundControl](http://qgroundcontrol.com/)
  - [Mission Planner](https://ardupilot.org/planner/index.html)
  - [MavProxy](https://ardupilot.org/mavproxy/docs/getting_started/index.html)

## Assignment

Prepare a flight plan:

<!-- - [Flight planning in eMotion 3 software]() -->
- [Flight plan analysis in GRASS GIS](assignments/assignment_1a_grass.qmd)

## Homework

Prepare a report on the flight plan: purpose, permits, map of the area boundary, with take off, landing, locations, ground control points and flight altitude analysis.
